- name: Copy and extract archive
  hosts: mc_server
  become: true
  gather_facts: false
  vars:
    new_dir: "Year of Blood"
    map_name: test
  vars_prompt:
    - name: map_name_input
      prompt: "Введи конечное имя карты (латиницей)"
      private: false
  tasks:
    - name: Make map name lowercase
      ansible.builtin.set_fact:
        map_name: "{{ map_name_input | lower }}"
    - ansible.builtin.debug:
        msg: "{{ map_name }}"

