- name: Copy and extract archive
  hosts: mc_server
  become: true
  gather_facts: false
  vars:
    new_dir: "Year of Blood"
    map_name: test
  # vars_prompt:
  #   - name: map_name
  #     prompt: "Введи конечное имя карты (латиницей)"
  #     private: false
  tasks:
    - name: Delete directory (if exists)
      ansible.builtin.file:
        path: "{{ bukkit }}/Gramm'in Gun"
        state: absent
    - name: Extract archive
      ansible.builtin.unarchive:
        src: "{{ maps }}/Grammin_Gun.zip"
        dest: "{{ bukkit }}"
        remote_src: true
        owner: minecraft
        group: minecraft
      become: true
      register: result
    - ansible.builtin.set_fact:
        new_dir: "{{ result.extract_results.out | regex_search(bukkit + '/(.*?)/') | regex_replace(bukkit + '/(.*?)/', '\\1') }}"

    - debug:
        # msg: "{{ result }}"
        msg: "{{ new_dir }}"
    - name: Rename directory
      ansible.builtin.command: mv "{{ bukkit }}/{{ new_dir }}" "{{ bukkit }}/{{ map_name }}"
      changed_when: false
