- name: Copy and extract archive
  hosts: mc_server
  become: true
  gather_facts: false
  vars:
    new_dir: "Year of Blood"
    map_name: test
  # vars_prompt:
  #   - name: map_name
  #     prompt: "Введи конечное имя карты (латиницей)"
  #     private: false
  tasks:
  - name: Ansible delete file wildcard
    find:
      paths: "{{ bukkit }}"
      patterns: "^test.*"
      use_regex: true
      file_type: directory
    register: wildcard_files_to_delete
  - name: debug
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ wildcard_files_to_delete.files }}"
    



  # - name: Ansible remove file wildcard
  #   file:
  #     path: "{{ item.path }}"
  #     state: absent
  #   with_items: "{{ wildcard_files_to_delete.files }}"
